version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: meu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Souza@2022
      MYSQL_DATABASE: db_biblioteca
      MYSQL_USER: biblioteca
      MYSQL_PASSWORD: Souza@2022
    ports:
      - ':3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
